name: Latest blog posts
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-articles:
    name: Update this repo's README with latest from blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.7.8
        with:
          comment_tag_name: "MERELA-ORG-POSTS"
          feed_list: "https://merela.org/rss.xml"
